### ISSUE TITLE
Custom context script

### ISSUE THREAD

**Issue by feldsam** [OpenNebula/docker-machine-opennebula#2]
Hello, I create Opnnebula tempalte with INIT_SCRIPTS key in CONTEXT. But it doesn't work, when machine is inicialized byt this driver, because driver itself create own CONTEXT. Solution would be merging CONTEXT defined in VM Template with driver context. Respectivelly, just add to CONTEXT your START_SCRIPT_BASE64

**Comment by jmelis** [comment]
After reviewing this, I believe this is more an enhancement than a bug. It was a design decision that those CONTEXT attributes were going to be substituted with a specific one provided by the docker-machine-opennebula plugin.

Changing this is possible, but not easy. I'm leaving this open in order to improve it in future releases, although I believe this is not something we will do in the short-term.

**Comment by feldsam** [comment]
Hello, so probably easier will be adding another option to driver, where can user pass custom context keys/values.

**Comment by jmelis** [comment]
Can you provide an example?

**Comment by feldsam** [comment]
Something like `--opennebula-files` and `--opennebula-init-scripts` which define context keys `FILES` and `INIT_SCRIPTS`

We bypassed this issue by calling docker-machine ssh 'commnads from init script' and it works fine....

so it can wait for template context merging implementation

**Comment by jmelis** [comment]
Thanks for explaining it. I prefer this solution than context merging, actually :+1:
